name: automated github pages

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools

      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish src/notepad.csproj -c Release -o dist/notepad-minus-minus --nologo

      # change base tag in all html files to include subfolder
      - name: Change base tag
        working-directory: dist/notepad-minus-minus/wwwroot
        run: |
          find . -name "*.html" | while read htmlFile; do
              sed -i 's/<base href="\/"/<base href="\/notepad-minus-minus\/"/g' $htmlFile
          done

      # copy index.html to 404.html to serve the same file when a file is not found
      - name: Copy index.html to 404.html
        run: cp dist/notepad-minus-minus/wwwroot/index.html dist/notepad-minus-minus/wwwroot/404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch dist/notepad-minus-minus/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/notepad-minus-minus/wwwroot
